# 更改配置文件名称
logging:
  # log4j2配置：classpath:log4j2-config.xml
  config: classpath:logging-config.xml
  # 通过配置文件改变指定包的日志输出级别
  level:
    org:
      springframework: info

spring:
  task:
    scheduling:
      thread-name-prefix: sbia-schedule-
      pool:
        size: 4
#  h2:
#    console:
#      # 控制台访问路径
#      path: /h2-console
#      # 是否启用控制台
#      enabled: true
#      # 是否允许远程访问
#      settings:
#        web-allow-others: true
#  datasource:
#    # 嵌入式数据库连接方式
#    embeddedDatabaseConnection: EmbeddedDatabaseConnection.H2
#    # 数据库名称
#    name: sbia_demo
#    # schema脚本
#    schema: classpath:sbia_demo_schema.sql
#    # 数据脚本
#    data: classpath:sbia_demo_data.sql
#    # 连接池类型
#    type: com.zaxxer.hikari.HikariDataSource
  datasource:
    url: jdbc:mysql://localhost:3306/sbia_demo?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    # 连接池类型
    type: com.zaxxer.hikari.HikariDataSource
  hikari: ##  Hikari 连接池配置 ------ 详细配置请访问：https://github.com/brettwooldridge/HikariCP
      ## 最小空闲连接数量
      minimum-idle: 5
      ## 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 180000
      ## 连接池最大连接数，默认是10
      maximum-pool-size: 10
      ## 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      ## 连接池名字
      pool-name: MyHikariCP
      ## 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 1800000
      ## 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 30000
      connection-test-query: SELECT 1

# mybatis
mybatis:
  type-aliases-package: com.tm.sbia.feature.domain
  check-config-location: false
  mapper-locations: classpath*:mapping/*Mapper.xml
  configuration:
    # 全局映射器启用缓存
    cache-enabled: true
    # 查询时，关闭关联对象即时加载以提高性能
    lazy-loading-enabled: true
    # 设置关联对象加载的形态，此处为按需加载字段(加载字段由SQL指 定)，不会加载关联表的所有字段，以提高性能
    aggressive-lazy-loading: false
    # 对于未知的SQL查询，允许返回不同的结果集以达到通用的效果
    multiple-result-sets-enabled: true
    # 允许使用列标签代替列名
    use-column-label: true
    # 给予被嵌套的resultMap以字段-属性的映射支持
    auto-mapping-behavior: FULL
    # 数据库超过25000秒仍未响应则超时
    default-statement-timeout: 0
    # 使用驼峰规则
    map-underscore-to-camel-case: true

